# Numpy
    考虑到读者分布，学习型笔记将采用中文
    
虽然用　Python　很久了，但是时常花一定时间学习一些新的操作还是能提高平时的编程效率的。其实，每种语言对于某一功能可能都有多种实现方式，我们在编程时就是在不断的compormise：　遇到不能直接实现的问题，就采用“曲线救国”的方法。如果一味追求知道尽可能多的操作，编程能力可能并不能有很大的提升。

In [1]:
# -*- coding: utf-8 -*-
import numpy as np

下面介绍一些常用的操作

In [2]:
c=np.array([[1,2],[3,4],[5,6]])

In [12]:
print(c.shape)      #返回数组的形状（shape）
print(c.size)       #返回数组的大小
print(c.max(axis=0))    # 这里的 axis 指的是某个轴变
print(c.mean(axis=0))
print(c.flatten())   # 无论之前是什么形状，一律变成一维向量
print(np.ravel(c))     #　同上

(3, 2)
6
[5 6]
[ 3.  4.]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [14]:
# 3x3的浮点型2维数组，并且初始化所有元素值为1
e = np.ones((3, 3), dtype=np.float)

 
# 创建一个一维数组，元素值是把3重复4次，array([3, 3, 3, 3])
f = np.repeat(3, 4)
l = np.arange(10)      # 类似range
print(l)


# 2x2x3的无符号8位整型3维数组，并且初始化所有元素值为0
g = np.zeros((2, 2, 3), dtype=np.uint8)
g.shape                    # (2, 2, 3)
h = g.astype(np.float)  # 用另一种类型表示
 

m = np.linspace(0, 6, 5)# 等差数列，0到6之间5个取值
print(m)

[0 1 2 3 4 5 6 7 8 9]
[ 0.   1.5  3.   4.5  6. ]


上面的例子中注意：1.　数据类型要用 `np.float`　2.　强制类型转换是　`.astype()`

## 数组的引用

In [16]:
a = np.arange(24).reshape((2, 3, 4))
b = a[1][1][1]  # 17
print(b)

b1 = a[1,1,1]
print(b1)

17
17


`a[1,1,1]`　和　`a[1][1][1]` 的引用方式完全一样

In [18]:
print(a[:,2,:])
print('\n')
print(a[:,[2],:])

[[ 8  9 10 11]
 [20 21 22 23]]


[[[ 8  9 10 11]]

 [[20 21 22 23]]]


这里想说一个非常重要但是常常被忽略的问题，就是在引用数组的时候，如果引用对象只有一个，那么就会发生降维现象，这样虽然看起来没有没什么问题，但是新得到的张量和原张量的维度信息并不同。为了避免这一情况发生，可以采用`a[:,[2],:]` 的方法。

In [19]:
print(a[:,:,1])
print('\n')
print(a[...,1])

[[ 1  5  9]
 [13 17 21]]


[[ 1  5  9]
 [13 17 21]]


`...` 指未指明的维度

数组的拼接可以使用： `vstack`、`hstack`，但是这里更推荐使用　`concatenate`

In [20]:
l0 = np.arange(6).reshape((2, 3))
l1 = np.arange(6, 12).reshape((2, 3))
print(l0)
print(l1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [21]:
m = np.hstack((l0, l1))
r = np.concatenate((l0, l1), axis=-1)
print(m)
print('\n')
print(r)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


这里还有一个函数　`stack`　和　`concatenate`，不同的是　`stack`　之后，维度会增加一

Numpy　模块的运算具有**广播**性质：

In [24]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
d = np.array([1, 2, 3])
print(c+d)
print('\n')
print(c+d.T)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [40]:
e = np.array([[1, 2, 3, 4]])
#print(c+e) this will raise an error
print('\n')
print(c+e.T)



[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


上面的例子再一次说明了：尽量少的使用一维向量，他们的模式不容易把握。

## Numpy强大的数学运算能力

实际上，numpy 具有强大的运算能力。比如SVD分解这些都可以直接做，这里提及只是再次强调，遇到简单的线性代数运算，不需要再寻找函数，只需要用numpy内部的函数即可。

## 随机模块

In [42]:
import numpy.random as random
 
# 设置随机数种子
random.seed(42)
 
# 产生一个1x3，[0,1)之间的浮点型随机数
# array([[ 0.37454012,  0.95071431,  0.73199394]])
# 后面的例子就不在注释中给出具体结果了
random.rand(1, 3)
 
# 产生一个[0,1)之间的浮点型随机数
random.random()
 
# 下边4个没有区别，都是按照指定大小产生[0,1)之间的浮点型随机数array，不Pythonic…
random.random((3, 3))
random.sample((3, 3))
random.random_sample((3, 3))
random.ranf((3, 3))
 
# 产生10个[1,6)之间的浮点型随机数
5*random.random(10) + 1
random.uniform(1, 6, 10)
 
# 产生10个[1,6]之间的整型随机数
random.randint(1, 6, 10)
 
# 产生2x5的标准正态分布样本
random.normal(size=(5, 2))
 
# 产生5个，n=5，p=0.5的二项分布样本
random.binomial(n=5, p=0.5, size=5)
 
a = np.arange(10)
 
# 从a中有回放的随机采样7个
random.choice(a, 7)
 
# 从a中无回放的随机采样7个
random.choice(a, 7, replace=False)
 
# 对a进行乱序并返回一个新的array
b = random.permutation(a)
 
# 对a进行in-place乱序
random.shuffle(a)
 
# 生成一个长度为9的随机bytes序列并作为str返回
# '\x96\x9d\xd1?\xe6\x18\xbb\x9a\xec'
random.bytes(9)

'\x8e\x063\x8a\xaa\xcck\xc1\x1c'

1.　随机矩阵
2.　制定范围的随机数/组
3.　随机整数/组
4.　二维标准正态分布
5.　二项分布
6.　有/无　放回抽样
7.　打乱